// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4K_zcnEW_u2tXn7-BBFFgYFTADZywWU',
    appId: '1:336816040437:web:3b376878a80725096ad8bc',
    messagingSenderId: '336816040437',
    projectId: 'ecocollect-app',
    authDomain: 'ecocollect-app.firebaseapp.com',
    storageBucket: 'ecocollect-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkc3bji-99DU09Baki6W1Jc4LVengK7TI',
    appId: '1:336816040437:android:1af644477345fe966ad8bc',
    messagingSenderId: '336816040437',
    projectId: 'ecocollect-app',
    storageBucket: 'ecocollect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YNw476cBcGVF9qSBZYNQ6IQw4xZsIDI',
    appId: '1:336816040437:ios:74ee684d32ad3a846ad8bc',
    messagingSenderId: '336816040437',
    projectId: 'ecocollect-app',
    storageBucket: 'ecocollect-app.firebasestorage.app',
    iosBundleId: 'com.example.ecocollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7YNw476cBcGVF9qSBZYNQ6IQw4xZsIDI',
    appId: '1:336816040437:ios:74ee684d32ad3a846ad8bc',
    messagingSenderId: '336816040437',
    projectId: 'ecocollect-app',
    storageBucket: 'ecocollect-app.firebasestorage.app',
    iosBundleId: 'com.example.ecocollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi4K_zcnEW_u2tXn7-BBFFgYFTADZywWU',
    appId: '1:336816040437:web:1a24d6624978f58a6ad8bc',
    messagingSenderId: '336816040437',
    projectId: 'ecocollect-app',
    authDomain: 'ecocollect-app.firebaseapp.com',
    storageBucket: 'ecocollect-app.firebasestorage.app',
  );

}